### ISSUE TITLE
publish as cocoapod?

### ISSUE THREAD

**Issue by jedi4ever** [hyukhur/RemoteLocalizable#1]
any chance you would publish/maintain this as a cocoa pod?

**Comment by hyukhur** [comment]
I'm not sure yet whether this source has the values.
in iOS 9, there is new feature that called "on-demand resources"
if you want it, I will do and improve it.
Thanks for your interest.

**Comment by jedi4ever** [comment]
no problem - I ended up using 
https://github.com/sirnicolaz/NMRemoteBundle
